library(devtools)
install.packages("spDataLarge",dependencies=TRUE,repos='https://nowosad.github.io/drat/', type='source')
install.packages("RColorBrewer",dependencies=TRUE,repos='https://nowosad.github.io/drat/', type='source')
install.packages("raster",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("sp",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("devtools",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("maptools",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("rgdal",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("rgeos",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("dplyr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tidyr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("stringr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("readxl",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("openxlsx",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("rasterVis",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("spatstat",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("latticeExtra",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("deldir",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("dismo",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("fields",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("geosphere",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("RandomFields",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("randomForest",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("rpart",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("sf",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("spdep",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("XML",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("spData",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("spgwr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("kernlab",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("Rwofost",dependencies=TRUE, repos='http://R-Forge.R-project.org')
install.packages("RStoolbox",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("landsat",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("hsdar",dependencies=TRUE, repos='http://cran.rstudio.com/')
library(devtools)
install_github("CIAT-DAPA/analogues")
install_github("palderman/dssatR")
install_github("agrobioinfoservices/climatrends", build_vignettes = TRUE)
install_github("agrobioinfoservices/gosset", build_vignettes = TRUE)
install_github("agrobioinfoservices/gdistance")
install_github("agrobioinfoservices/ClimMobTools")
install.packages("vroom",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("future",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("furrr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("doSNOW",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("earth",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("FactoMineR",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("parallelDist",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("terra",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("trend",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("climatrends",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("caretEnsemble",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ggspatial",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("adehabitatHR",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tcltk2",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ggplot2",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("fastcluster",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("foreach",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tidyverse",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("cluster",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("stringr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("glue",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("pacman",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("purrr",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("fst",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("lubridate",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("sdm",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("distances",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("rlang",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("gdistance",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("caret",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("bindrcpp",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("proc",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("maxnet",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("usdm",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("tictoc",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("snow",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("gtools",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("domc",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ade4",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("doParallel",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("adehabitatHR",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ggspatial",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("doMC",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("caretEnsemble",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("proj4",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("RMAWGEN",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("meteor",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("Hmisc",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("mclust",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("fpc",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("Rquefts",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("reshape",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("DSSAT",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("Dasst",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("anytime",dependencies=TRUE, repos='http://cran.rstudio.com/')
library(devtools)
install_github("cropmodels/Recocrop")
install_github("ropensci/rgbif")
install_git('https://gitlab.croptrust.org/genesys-pgr/genesysr')
remotes::install_github("reagro/agro")
remotes::install_github("reagro/carobiner")
