tryCatch({library(devtools)},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("spDataLarge",repos='https://nowosad.github.io/drat/', type='source')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("RColorBrewer",repos='https://nowosad.github.io/drat/', type='source')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("raster", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("sp", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("devtools", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("maptools", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rgdal", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rgeos", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("dplyr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("tidyr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("stringr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("readxl", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("openxlsx", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rasterVis", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("spatstat", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("latticeExtra", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("deldir", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("dismo", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("fields", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("geosphere", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("RandomFields", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("randomForest", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rpart", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("sf", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("spdep", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("XML", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("spData", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("spgwr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("kernlab", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("Rwofost", repos='http://R-Forge.R-project.org')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("RStoolbox", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("landsat", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("hsdar", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({library(devtools)},error=function(e)e,warning=function(w)w)
tryCatch({install_github("CIAT-DAPA/analogues")},error=function(e)e,warning=function(w)w)
tryCatch({install_github("palderman/dssatR")},error=function(e)e,warning=function(w)w)
tryCatch({install_github("agrobioinfoservices/climatrends", build_vignettes = TRUE)},error=function(e)e,warning=function(w)w)
tryCatch({install_github("agrobioinfoservices/gosset", build_vignettes = TRUE)},error=function(e)e,warning=function(w)w)
tryCatch({install_github("agrobioinfoservices/gdistance")},error=function(e)e,warning=function(w)w)
tryCatch({install_github("agrobioinfoservices/ClimMobTools")},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("vroom", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("future", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("furrr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("doSNOW", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("earth", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("FactoMineR", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("parallelDist", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("trend", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("climatrends", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("caretEnsemble", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("ggspatial", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("adehabitatHR", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("tcltk2", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("ggplot2", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("fastcluster", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("foreach", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("tidyverse", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("cluster", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("stringr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("glue", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("pacman", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("purrr", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("fst", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("lubridate", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("sdm", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("distances", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rlang", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("gdistance", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("caret", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("bindrcpp", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("proc", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("maxnet", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("usdm", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("tictoc", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("snow", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("gtools", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("domc", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("ade4", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("doParallel", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("adehabitatHR", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("ggspatial", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("doMC", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("caretEnsemble", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("proj4", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("RMAWGEN", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("meteor", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("Hmisc", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("mclust", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("fpc", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("Rquefts", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("reshape", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("DSSAT", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("Dasst", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("anytime", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({library(devtools)},error=function(e)e,warning=function(w)w)
tryCatch({install_github("cropmodels/Recocrop")},error=function(e)e,warning=function(w)w)
tryCatch({install_github("ropensci/rgbif")},error=function(e)e,warning=function(w)w)
library(devtools)
tryCatch({install.packages("pROC",dependencies=TRUE, repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("rgbif",dependencies=TRUE, repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({devtools::install_git('https://gitlab.croptrust.org/genesys-pgr/genesysr')},error=function(e)e,warning=function(w)w)
tryCatch({install.packages("terra", repos='http://cran.rstudio.com/')},error=function(e)e,warning=function(w)w)
tryCatch({remotes::install_github("rspatial/luna")},error=function(e)e,warning=function(w)w)

