library(devtools)
install_github("CIAT-DAPA/analogues")
install_github("palderman/dssatR")
install_github("agrobioinfoservices/climatrends", build_vignettes = TRUE)
install_github("agrobioinfoservices/gosset", build_vignettes = TRUE)
install_github("agrobioinfoservices/gdistance")
install_github("agrobioinfoservices/ClimMobTools")
install.packages("vroom", repos='http://cran.rstudio.com/')
install.packages("future", repos='http://cran.rstudio.com/')
install.packages("furrr", repos='http://cran.rstudio.com/')
install.packages("doSNOW", repos='http://cran.rstudio.com/')
install.packages("earth", repos='http://cran.rstudio.com/')
install.packages("FactoMineR", repos='http://cran.rstudio.com/')
install.packages("parallelDist", repos='http://cran.rstudio.com/')
install.packages("trend", repos='http://cran.rstudio.com/')
install.packages("climatrends", repos='http://cran.rstudio.com/')
install.packages("caretEnsemble", repos='http://cran.rstudio.com/')
install.packages("ggspatial", repos='http://cran.rstudio.com/')
install.packages("adehabitatHR", repos='http://cran.rstudio.com/')
install.packages("tcltk2", repos='http://cran.rstudio.com/')
install.packages("ggplot2", repos='http://cran.rstudio.com/')
install.packages("fastcluster", repos='http://cran.rstudio.com/')
install.packages("foreach", repos='http://cran.rstudio.com/')
install.packages("tidyverse", repos='http://cran.rstudio.com/')
install.packages("cluster", repos='http://cran.rstudio.com/')
install.packages("stringr", repos='http://cran.rstudio.com/')
install.packages("glue", repos='http://cran.rstudio.com/')
install.packages("pacman", repos='http://cran.rstudio.com/')
install.packages("purrr", repos='http://cran.rstudio.com/')
install.packages("fst", repos='http://cran.rstudio.com/')
install.packages("lubridate", repos='http://cran.rstudio.com/')
install.packages("sdm", repos='http://cran.rstudio.com/')
install.packages("distances", repos='http://cran.rstudio.com/')
install.packages("rlang", repos='http://cran.rstudio.com/')
install.packages("gdistance", repos='http://cran.rstudio.com/')
install.packages("caret", repos='http://cran.rstudio.com/')
install.packages("bindrcpp", repos='http://cran.rstudio.com/')
install.packages("proc", repos='http://cran.rstudio.com/')
install.packages("maxnet", repos='http://cran.rstudio.com/')
install.packages("usdm", repos='http://cran.rstudio.com/')
install.packages("tictoc", repos='http://cran.rstudio.com/')
install.packages("snow", repos='http://cran.rstudio.com/')
install.packages("gtools", repos='http://cran.rstudio.com/')
install.packages("domc", repos='http://cran.rstudio.com/')
install.packages("ade4", repos='http://cran.rstudio.com/')
install.packages("doParallel", repos='http://cran.rstudio.com/')
install.packages("adehabitatHR", repos='http://cran.rstudio.com/')
install.packages("ggspatial", repos='http://cran.rstudio.com/')
install.packages("doMC", repos='http://cran.rstudio.com/')
install.packages("caretEnsemble", repos='http://cran.rstudio.com/')
install.packages("proj4", repos='http://cran.rstudio.com/')
install.packages("RMAWGEN", repos='http://cran.rstudio.com/')
install.packages("meteor", repos='http://cran.rstudio.com/')
install.packages("Hmisc", repos='http://cran.rstudio.com/')
library(devtools)
install_github("rspatial/terra")
install_github("cropmodels/Recocrop")










